version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/memozy-back
    overwrite: yes

permissions:
  - object: /home/ubuntu/memozy-back
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu