spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
    open-in-view: false

  # (선택) 로깅 포맷
  output:
    ansi:
      enabled: always

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-version: 0

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

jwt:
  access-key: ${JWT_ACCESS_KEY}
  refresh-key: ${JWT_REFRESH_KEY}
  accessExpiredMin: ${JWT_ACCESS_EXPIRED_MIN}
  refreshExpiredDay: ${JWT_REFRESH_EXPIRED_DAY}
  bearerPrefix: Bearer

oauth2:
  client:
    kakao:
      client-id: ${KAKAO_CLIENT_ID}
      redirect-path: http://localhost:8080/auth/login/kakao
      grant-type: authorization_code
      content-type: application/x-www-form-urlencoded;charset=utf-8
      login-page-url: https://kauth.kakao.com/oauth/authorize?response_type=code

aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}

server:
  address: 127.0.0.1
  port: 8080

openai:
  api-key: ${OPENAI_API_KEY}
  model: ${OPENAI_API_MODEL}
