name: CI/CD Pipeline

# main 브랜치에 push 또는 pull request가 발생할 때 실행
# feature/{feature-name} : 새로운 기능이나 버그 수정 작업 브랜치
on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: memozy-back
  BUCKET_NAME: memozy-bucket
  CODE_DEPLOY_APP_NAME: memozy
  DEPLOYMENT_GROUP_NAME: memozy-group
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  AWS_REGION: ap-northeast-2

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Create application.yml
        run: echo "${{ secrets.APPLICATION_PROD_YML }}" > src/main/resources/application.yml

      - name: Generate docker-compose.yml from GitHub Secret
        run: |
          echo "${{ secrets.DOCKER_COMPOSE_PROD_YML }}" > docker-compose.yml

      # gradlew 파일 실행권한 설정
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 빌드 시작
      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Mask Secrets
        run: |
          echo "::add-mask::${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "::add-mask::${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      # aws 접근 id, key
      - name: Configure AWS credentials
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_REGION: ${{ env.AWS_REGION }}

      - name: Docker Image Build And Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:prod
          platforms: linux/amd64
          pull: true

      - name: Make deployment zip
        run: zip -qq -r ${{ github.sha }}.zip . -x '*.git*'

      - name: Upload to S3
        run: aws s3 cp ./${{ github.sha }}.zip s3://${{ env.BUCKET_NAME }}/${{ env.PROJECT_NAME }}/${{ github.sha }}.zip

      - name: Create CodeDeploy Deployment
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.CODE_DEPLOY_APP_NAME }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name ${{ env.DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=${{ env.BUCKET_NAME }},bundleType=zip,key=${{ env.PROJECT_NAME }}/${{ github.sha }}.zip